# Generated by Django 3.0.5 on 2020-05-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Pictures',
        ),
        migrations.AddField(
            model_name='messages',
            name='MessageSent',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Picture1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='Picture2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='Picture3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='Picture4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='Picture5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='Picture6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='Picture7',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='messages',
            name='MessageID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_product', to='main_app.Products'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='UserIDFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFrom', to='main_app.Users'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='UserIDTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTo', to='main_app.Users'),
        ),
        migrations.AlterField(
            model_name='products',
            name='ProductID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main_app.Users'),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('likeId', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_product', to='main_app.Products')),
                ('user', models.ManyToManyField(related_name='like_users', to='main_app.Users')),
            ],
        ),
    ]
