# Generated by Django 3.0.5 on 2020-05-03 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200503_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hates',
            fields=[
                ('HateID', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hated_product', to='main_app.Products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hate_users', to='main_app.Users')),
            ],
        ),
    ]
